language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm
env:
  - PREFER_LOWEST="--prefer-lowest"
  - PREFER_LOWEST=""

before_script:
    - composer self-update
    - composer update --prefer-dist --no-interaction $PREFER_LOWEST

script:
    - ./bin/phpunit --coverage-text
